apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis-ha-haproxy
  namespace: argocd
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: argocd-application-controller
          env:
            - name: ARGOCD_REDIS_HA_HAPROXY_REPLICAS
              value: "2"